; PlatformIO 项目配置文件
; 板卡: Arduino UNO R3 (CH340 兼容板)
; 作用: USB转GPIO/PWM/ADC 扩展执行器，不含任何业务决策逻辑

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; 串口通信速率，需与 i.MX93 端一致
monitor_speed = 115200
upload_speed = 115200

; 依赖库
lib_deps =
    arduino-libraries/Servo@^1.2.2
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
